/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupRouteImport } from './routes/$group'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GroupIndexRouteImport } from './routes/$group/index'
import { Route as GroupFearlessRouteImport } from './routes/$group/fearless'
import { Route as GroupInsightsRouteImport } from './routes/$group/insights'
import { Route as GroupRouletteRouteImport } from './routes/$group/roulette'
import { Route as GroupCustomsIndexRouteImport } from './routes/$group/customs/index'
import { Route as GroupCustomsIdRouteImport } from './routes/$group/customs/$id'
import { Route as GroupPlayersMemberRouteImport } from './routes/$group/players/$member'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupRoute = GroupRouteImport.update({
  id: '/$group',
  path: '/$group',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupIndexRoute = GroupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupRoute,
} as any)
const GroupFearlessRoute = GroupFearlessRouteImport.update({
  id: '/fearless',
  path: '/fearless',
  getParentRoute: () => GroupRoute,
} as any)
const GroupInsightsRoute = GroupInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => GroupRoute,
} as any)
const GroupRouletteRoute = GroupRouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => GroupRoute,
} as any)
const GroupCustomsIndexRoute = GroupCustomsIndexRouteImport.update({
  id: '/customs/',
  path: '/customs/',
  getParentRoute: () => GroupRoute,
} as any)
const GroupCustomsIdRoute = GroupCustomsIdRouteImport.update({
  id: '/customs/$id',
  path: '/customs/$id',
  getParentRoute: () => GroupRoute,
} as any)
const GroupPlayersMemberRoute = GroupPlayersMemberRouteImport.update({
  id: '/players/$member',
  path: '/players/$member',
  getParentRoute: () => GroupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$group': typeof GroupRouteWithChildren
  '/admin': typeof AdminRoute
  '/$group/fearless': typeof GroupFearlessRoute
  '/$group/insights': typeof GroupInsightsRoute
  '/$group/roulette': typeof GroupRouletteRoute
  '/$group/': typeof GroupIndexRoute
  '/$group/customs/$id': typeof GroupCustomsIdRoute
  '/$group/players/$member': typeof GroupPlayersMemberRoute
  '/$group/customs/': typeof GroupCustomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/$group/fearless': typeof GroupFearlessRoute
  '/$group/insights': typeof GroupInsightsRoute
  '/$group/roulette': typeof GroupRouletteRoute
  '/$group': typeof GroupIndexRoute
  '/$group/customs/$id': typeof GroupCustomsIdRoute
  '/$group/players/$member': typeof GroupPlayersMemberRoute
  '/$group/customs': typeof GroupCustomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$group': typeof GroupRouteWithChildren
  '/admin': typeof AdminRoute
  '/$group/fearless': typeof GroupFearlessRoute
  '/$group/insights': typeof GroupInsightsRoute
  '/$group/roulette': typeof GroupRouletteRoute
  '/$group/': typeof GroupIndexRoute
  '/$group/customs/$id': typeof GroupCustomsIdRoute
  '/$group/players/$member': typeof GroupPlayersMemberRoute
  '/$group/customs/': typeof GroupCustomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$group'
    | '/admin'
    | '/$group/fearless'
    | '/$group/insights'
    | '/$group/roulette'
    | '/$group/'
    | '/$group/customs/$id'
    | '/$group/players/$member'
    | '/$group/customs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/$group/fearless'
    | '/$group/insights'
    | '/$group/roulette'
    | '/$group'
    | '/$group/customs/$id'
    | '/$group/players/$member'
    | '/$group/customs'
  id:
    | '__root__'
    | '/'
    | '/$group'
    | '/admin'
    | '/$group/fearless'
    | '/$group/insights'
    | '/$group/roulette'
    | '/$group/'
    | '/$group/customs/$id'
    | '/$group/players/$member'
    | '/$group/customs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupRoute: typeof GroupRouteWithChildren
  AdminRoute: typeof AdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$group': {
      id: '/$group'
      path: '/$group'
      fullPath: '/$group'
      preLoaderRoute: typeof GroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$group/': {
      id: '/$group/'
      path: '/'
      fullPath: '/$group/'
      preLoaderRoute: typeof GroupIndexRouteImport
      parentRoute: typeof GroupRoute
    }
    '/$group/fearless': {
      id: '/$group/fearless'
      path: '/fearless'
      fullPath: '/$group/fearless'
      preLoaderRoute: typeof GroupFearlessRouteImport
      parentRoute: typeof GroupRoute
    }
    '/$group/insights': {
      id: '/$group/insights'
      path: '/insights'
      fullPath: '/$group/insights'
      preLoaderRoute: typeof GroupInsightsRouteImport
      parentRoute: typeof GroupRoute
    }
    '/$group/roulette': {
      id: '/$group/roulette'
      path: '/roulette'
      fullPath: '/$group/roulette'
      preLoaderRoute: typeof GroupRouletteRouteImport
      parentRoute: typeof GroupRoute
    }
    '/$group/customs/': {
      id: '/$group/customs/'
      path: '/customs'
      fullPath: '/$group/customs/'
      preLoaderRoute: typeof GroupCustomsIndexRouteImport
      parentRoute: typeof GroupRoute
    }
    '/$group/customs/$id': {
      id: '/$group/customs/$id'
      path: '/customs/$id'
      fullPath: '/$group/customs/$id'
      preLoaderRoute: typeof GroupCustomsIdRouteImport
      parentRoute: typeof GroupRoute
    }
    '/$group/players/$member': {
      id: '/$group/players/$member'
      path: '/players/$member'
      fullPath: '/$group/players/$member'
      preLoaderRoute: typeof GroupPlayersMemberRouteImport
      parentRoute: typeof GroupRoute
    }
  }
}

interface GroupRouteChildren {
  GroupFearlessRoute: typeof GroupFearlessRoute
  GroupInsightsRoute: typeof GroupInsightsRoute
  GroupRouletteRoute: typeof GroupRouletteRoute
  GroupIndexRoute: typeof GroupIndexRoute
  GroupCustomsIdRoute: typeof GroupCustomsIdRoute
  GroupPlayersMemberRoute: typeof GroupPlayersMemberRoute
  GroupCustomsIndexRoute: typeof GroupCustomsIndexRoute
}

const GroupRouteChildren: GroupRouteChildren = {
  GroupFearlessRoute: GroupFearlessRoute,
  GroupInsightsRoute: GroupInsightsRoute,
  GroupRouletteRoute: GroupRouletteRoute,
  GroupIndexRoute: GroupIndexRoute,
  GroupCustomsIdRoute: GroupCustomsIdRoute,
  GroupPlayersMemberRoute: GroupPlayersMemberRoute,
  GroupCustomsIndexRoute: GroupCustomsIndexRoute,
}

const GroupRouteWithChildren = GroupRoute._addFileChildren(GroupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupRoute: GroupRouteWithChildren,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
